### ISSUE TITLE
crash when picking up a cow with a piggyback

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATC#6]
reported by @StrommKral#5871 -- need more research and possible report to TiCo

**Comment by OrdinatorStouff** [comment]
Some more details thanks to @thecodewarrior in Discord:

[10:36 AM] thecodewarrior: It's this: slimeknights.tconstruct.gadgets.item.ItemPiggybackPack$CarryPotionEffect.func_76394_a(ItemPiggybackPack.java:195) ~[ItemPiggybackPack$CarryPotionEffect.class:?]
[10:36 AM] thecodewarrior: They pass null as the capability
[10:36 AM] thecodewarrior: which then ripples down to all the capability providers
[10:37 AM] thecodewarrior: and since mine is kotlin it enforces non-nullability

So possibly the issue is somewhere between Tinker's Piggyback item and the Rustic (non vanilla) cows and the cap was null and should not be.

**Comment by thecodewarrior** [comment]
I don't believe it has anything to do with the specific entity. Somehow `CapabilityTinkerPiggyback.PIGGYBACK` is null.

**Comment by thecodewarrior** [comment]
Well, `CapabilityTinkerPiggyback.register()` never seems to be called, at least from a cursory search in github.

**Comment by KnightMiner** [comment]
Huh, weird. I could have sworn the call to register happened before.

For the record, its a piggybackpack. You need the pack.

**Comment by thecodewarrior** [comment]
It probably worked before because of two things:

1. Nobody did anything with the capability except check equality, which
doesn't pose problems with a null value
2. Your capability was the only one on the player that checked its input
against null (because you pass null, but then check against null) so your
cap returned

The problem only surfaced when my capability provider (which is written in
kotlin, which has explicit nullability and runtime null checks) was passed
null for the cap. It still however would have caused nearly untraceable
class cast errors when another mod that mistakenly used a null cap was
present.

**Comment by KnightMiner** [comment]
Yeah, I think it caused one issue before but that was quickly closed when the other author figured out they were passing in null, I guess we forgot to verify we were not passing null.

It was created when capabilities were fairly new so there wee a few other issues originally, just never caught this one

**Comment by OrdinatorStouff** [comment]
@KnightMiner I haven't checked in on this in a while... do we know if this got resolved already?

**Comment by StrommKral** [comment]
the issues is solved, picked up cow,pig,lama,chicken,sheep and horse, all is fine

**Comment by KnightMiner** [comment]
Yep, the commit which fixed this is in a build.

**Comment by OrdinatorStouff** [comment]
Thanks for confirming @KnightMiner and @StrommKral  :D 👍
